name: Node.js CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 24
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        cache: 'npm'

    - name: Install Dependencies
      run: npm install  # We use 'install' instead of 'ci' just in case the lockfile is out of sync

    - name: Build Source
      run: npm run build
      env:
        NODE_OPTIONS: "--max-old-space-size=4096" # Boosts memory for Vite 8

    - name: Deploy to Firebase
      # This only runs if the build succeeds
      run: npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive