name: Travella Deployment
on:
  push:
    branches: [ "main" ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'

      - name: Install Dependencies
        # Using install instead of ci to fix any lockfile drift
        run: npm install 

      - name: Build Project
        # CI=false prevents "Warnings" from being treated as "Errors"
        run: CI=false npm run build 
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Deploy to Firebase
        # We use npx to ensure we use the latest firebase-tools without a global install
        run: npx firebase-tools deploy --only hosting --token "${{ secrets.FIREBASE_TOKEN }}" --non-interactive